controllers/AdminController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

class AdminController extends Controller {

    public $session;
    public $nav = null;
    public $title = null;
    public $layout = 'main';

    public function __construct($id, $module, $config = array()) {
        parent::__construct($id, $module, $config);
        $this->session = Yii::$app->session;
        $this->session->open();

        if (!$this->session['auth']) {
            $target = Yii::$app->getUrlManager()->createUrl('site/index');
            Yii::$app->response->redirect($target);
        }

        $data['auth'] = $this->session['auth'];
        $this->nav = $this->renderPartial("nav_menu", $data);
    }

    public function actionIndex() {
        $this->title = "Welcome Page";
        $data['auth'] = $this->session['auth'];
        $user = \app\models\ExtUser::find()->all();
        $data["user"] = array();
        foreach ($user as $each_user) {
            $data["user"][$each_user->uid] = array();
            foreach ($each_user as $label => $val) {
                $data["user"][$each_user->uid][$label] = $val;
            }
        }
        if ($this->session['auth']['level'] == 1) {
            $data['file'] = \app\models\ExtUpload::find()->all();
        } else {
            $data['file'] = \app\models\ExtUpload::find()->where(["uid" => $this->session['auth']['uid']])->orderBy("upload_id")->all();
        }

        $data['file_admin'] = \app\models\ExtUpload::find()->join("INNER JOIN", "ext_user", "ext_user.uid = ext_upload.uid")->where(["ext_user.level" => 1])->orderBy("upload_id")->all();
        return $this->render("welcome", $data);
    }

    public function actionFileinfo() {
        $upload_id = \Yii::$app->getRequest()->get("upload_id", null);
        if ($upload_id) {
            $data['file'] = \app\models\ExtUpload::find()->where(["upload_id" => $upload_id])->one();
            $data["user"] = \app\models\ExtUser::find()->where(["uid" => $data["file"]->uid])->one();
            return $this->render("fileinfo", $data);
        } else {
            $target = Yii::$app->getUrlManager()->createUrl('admin/index');
            Yii::$app->response->redirect($target);
        }
    }

    public function actionListuser() {
        $this->title = "List all user";
        if ($this->session['auth']['level'] == 1) {
            $province = \Yii::$app->getRequest()->get("province", null);
            if ($province == null) {
                $data['user'] = \app\models\ExtUser::find()->orderBy('province')->all();
            } else {
                $data['user'] = \app\models\ExtUser::find()->where(["province" => $province])->orderBy('province')->all();
            }
            $data['province'] = $province;
        } else {
            $data['user'] = \app\models\ExtUser::find()->orderBy('province')->where(["province" => $this->session["auth"]["province"]])->all();
        }
        return $this->render("listuser", $data);
    }

    public function actionCreateuser() {
        $this->title = "Create user";
        return $this->render("createuser");
    }

    public function actionUserinfo() {
        $uid = \Yii::$app->getRequest()->get("uid", null);
        if ($uid != null) {
            $data['userinfo'] = \app\models\ExtUser::find()->where(["uid" => $uid])->one();
            $this->title = $data['userinfo']->realname;
            if (($this->session['auth']['uid'] == $uid) || ($this->session['auth']['level'] == 1)) {
                return $this->render("userinfo_edit", $data);
            } else {
                return $this->render("userinfo_view", $data);
            }
        } else {
            $target = \Yii::$app->urlManager->createUrl("admin/listuser");
            \Yii::$app->response->redirect($target);
        }
    }

    public function actionUpload() {
        $this->title = "Upload File";
        return $this->render("uploadfile");
    }

    public function __destruct() {
        $this->session->close();
    }

}

controllers/ApiController.php
<?php

namespace app\controllers;

use Yii;
use yii\base\Controller;

class ApiController extends Controller {

    public $session;

    public function __construct($id, $module, $config = array()) {
        parent::__construct($id, $module, $config);
        $this->session = Yii::$app->session;
        $this->session->open();

        if (!$this->session['auth']) {
            $target = Yii::$app->getUrlManager()->createUrl('site/index');
            Yii::$app->response->redirect($target);
        }
    }

    public function actionCreateuser() {
        $data = \Yii::$app->getRequest()->post();
        $store = new \app\models\ExtUser;
        foreach ($data as $index => $value) {
            $store->{$index} = ($index != "password") ? $value : md5($value);
        }
        if ($store->save()) {
            $resp['uid'] = $store->uid;
            $resp['status'] = "success";
            $resp['link'] = \Yii::$app->urlManager->createUrl("admin/listuser");
            // New User
            $username = \Yii::$app->getRequest()->post("username");
            $email = \Yii::$app->getRequest()->post("email");
            $realname = \Yii::$app->getRequest()->post("realname");
            $pre_hash_password = \Yii::$app->getRequest()->post("password");
            $body = "<h3>Welcome to FDACMI system</h3>";
            $body .= "<p>Hello {$realname}, here is your information</p>";
            $body .= "<p><b>Username</b>: {$username}</p>";
            $body .= "<p><b>Password</b>: {$pre_hash_password}</p>";
            $body .= "<p><i>You can login at <a href=" . \Yii::$app->urlManager->createUrl("") . ">FDACMI system</a></i></p>";

            $this->actionMailer($email, "New Registration", $body);
        } else {
            $resp['status'] = "fail";
        }
        echo json_encode($resp);
    }

    public function actionUpdateuser() {
        $data = \Yii::$app->getRequest()->post();
        $store = \app\models\ExtUser::find()->where(["uid" => $data['uid']])->one();
        unset($data["uid"]);
        unset($data["username"]);
        foreach ($data as $index => $value) {
            if ($index != "password") {
                $store->{$index} = $value;
            } elseif ($value != "xxxxx") {
                $store->{$index} = md5($value);
            }
        }

        if ($store->save()) {
            $email = \Yii::$app->getRequest()->post("email");
            $realname = \Yii::$app->getRequest()->post("realname");
            $body = "<h3>Hi, {$realname}</h3>";
            $body .= "<p>Your FDACMI Acc has updated</p>";
            $this->actionMailer($email, "Account updated", $body);
            $resp['status'] = "success";
        } else {
            $resp['status'] = "fail";
        }
        echo json_encode($resp);
    }

    public function actionUploadallfile() {
        $post = \Yii::$app->getRequest()->post();
        $folder = date('U');
//        $fpath = \Yii::$app->basePath;
//        $fpath .= "\\upload\\{$this->session["auth"]["uid"]}";

        $fpath = "./upload";
        if (!file_exists($fpath)) {
            @mkdir($fpath);
        }
        
        $fpath .= "/{$this->session["auth"]["uid"]}";
        if (!file_exists($fpath)) {
            @mkdir($fpath);
        }

        $fpath .= "/{$folder}";
        if (!file_exists($fpath)) {
            @mkdir($fpath);
        }

        $store = new \app\models\ExtUpload;
        foreach ($post as $label => $val) {
            $store->{$label} = $val;
        }
        $store->uid = $this->session['auth']['uid'];

        $upload_file = \yii\web\UploadedFile::getInstanceByName("file_upload_zxc");
        $saveFile = "{$fpath}/{$upload_file->name}";
        $upload_file->saveAs($saveFile);
        $store->upload_file = \Yii::$app->urlManager->hostInfo . \Yii::$app->urlManager->baseUrl . "/upload/{$this->session["auth"]["uid"]}/{$folder}/{$upload_file->name}";
        if ($store->save()) {
            $data["status"] = "success";
            $data["link"] = \Yii::$app->urlManager->createUrl("admin/index");
            $body = "<h3>Hi, {$this->session['auth']['realname']}</h3>";
            $body .= "<p>You have new file upload in list {$store->upload_file}</p>";
            if ($this->session['auth']['level'] == 1) {
                //Multiple Email
                $all_user = \app\models\ExtUser::find()->all();
                $from_mail = array();
                foreach ($all_user as $user) {
                    array_push($from_mail, $user->email);
                }
            } else {
                //Single Mail
                $from_mail = $this->session['auth']["email"];
            }
            $this->actionMailer($from_mail, "New file upload", $body);
        } else {
            $data["status"] = "fail";
        }
        echo json_encode($data);
    }

    public function actionMailer($to, $subject, $body, $return = true) {
        $to = isset($to) ? $to : \Yii::$app->getRequest()->post("to", null);
        $subject = isset($subject) ? $subject : \Yii::$app->getRequest()->post("subject", null);
        $body = isset($body) ? $body : \Yii::$app->getRequest()->post("body", null);
        $resp = \Yii::$app->mailer->compose()->setFrom("no-reply@fdacmi.co.th")->setBcc(\Yii::$app->params['adminEmail'])->setTo($to)->setSubject($subject)->setHtmlBody($body)->send();

        if ($resp) {
            $r = true;
            $data['status'] = "success";
        } else {
            $r = false;
            $data['status'] = "fail";
        }

        if ($return) {
            return $r;
        } else {
            echo json_encode($data);
        }
    }

    public function actionDebug() {
        echo \Yii::$app->urlManager->hostInfo . \Yii::$app->urlManager->baseUrl;
    }

    public function __destruct() {
        $this->session->close();
    }

}

views/admin/createuser.php
<div class="container">
    <div class="row" style="background-color: #efefef;">
        <div class="col-xs-3">
            <div class="panel panel-default" style="margin-top: 15px;">
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="<?php echo Yii::$app->urlManager->createUrl("admin/listuser") ?>">List of User</a></li>
                        <?php if (Yii::$app->controller->session["auth"]["level"] == 1): ?>
                            <li><a href="<?php echo Yii::$app->urlManager->createUrl("admin/createuser") ?>">Create new User</a></li>
                        <?php endif; ?>
                        <li><a href="<?php echo Yii::$app->urlManager->createUrl(["admin/userinfo", "uid" => Yii::$app->controller->session["auth"]["uid"]]) ?>">My Profile</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xs-9" style="background-color: #fff;">
            <h3>Application form</h3>
            <form class="form-horizontal" method="post" action="<?php echo Yii::$app->urlManager->createUrl("api/createuser") ?>" id="regist_form">
                <label>ชื่อ - นามสกุล</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input type="text" class="form-control" name="realname" placeholder="ชื่อ สกุล" required="">
                    </div>
                </div>

                <label>Username</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input type="text" class="form-control" name="username" placeholder="ชื่อเข้าใช้งาน" required="">
                    </div>
                </div>

                <label>Password</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input type="password" class="form-control" name="password" placeholder="รหัสผ่านเข้าใช้งาน" required="">
                    </div>
                </div>

                <label>Email</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input type="email" class="form-control" name="email" placeholder="Email" required="">
                    </div>
                </div>

                <label>ระดับผู้ใช้งาน</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <select name="level" class="form-control">
                            <?php foreach (Yii::$app->params["userlevel"] as $val => $label): ?>
                                <option value="<?php echo $val ?>"><?php echo $label ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <label>ประจำอำเภอ</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <select name="province" class="form-control">
                            <?php foreach (Yii::$app->params["amphor"] as $val => $label): ?>
                                <option value="<?php echo $val ?>"><?php echo $label ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-12">
                        <button type="submit" class="btn btn-primary" id="submit_btn" data-loading-text="Creating..."><i class="glyphicon glyphicon-upload"></i>&nbsp;Create</button>
                        <button type="reset" class="btn btn-danger"><i class="glyphicon glyphicon-refresh"></i>&nbsp;Reset</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script typr="text/javascript">
    $(function() {
        $('#regist_form').ajaxForm({
            beforeSend: function() {
                $('#submit_btn').button('loading');
            },
            complete: function(xhr) {
                var json = $.parseJSON(xhr.responseText);
                if (json.status === "success") {
                    swal({"title": "สำเร็จ", "text": "ระบบได้ทำการสร้างบัญชีผู้ใช้ใหม่เรียบร้อยแล้ว", "type": "success"}, function() {
                        location.href = json.link;
                    });
                } else {
                    swal({"title": "ล้มเหลว", "text": "ระบบไม่สามารถสร้างบัญชี", "type": "error"});
                }
                $('#submit_btn').button('reset');
            }
        });
    });
</script>

views/admin/listuser.php
<div class="container">
    <div class="row" style="background-color: #efefef;">
        <div class="col-xs-3">
            <div class="panel panel-default" style="margin-top: 15px;">
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="<?php echo Yii::$app->urlManager->createUrl("admin/listuser") ?>">List of User</a></li>
                        <?php if (Yii::$app->controller->session["auth"]["level"] == 1): ?>
                            <li><a href="<?php echo Yii::$app->urlManager->createUrl("admin/createuser") ?>">Create new User</a></li>
                        <?php endif; ?>
                        <li><a href="<?php echo Yii::$app->urlManager->createUrl(["admin/userinfo", "uid" => Yii::$app->controller->session["auth"]["uid"]]) ?>">My Profile</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xs-9" style="background-color: #fff;">
            <?php if (Yii::$app->controller->session["auth"]["level"] == 1): ?>
                <form class='form-horizontal'>
                    <div class='form-group'>
                        <label class='control-label col-xs-1'>Filter:</label>
                        <div class='col-xs-6'>
                            <select class='form-control' name='province' style='width: 213px !important; display: inline-block;'>
                                <option value="">ทุกอำเภอ</option>
                                <?php foreach (Yii::$app->params["amphor"] as $val => $label): ?>
                                    <option value="<?php echo $val ?>" <?php echo $province == $val ? "selected" : ""; ?>><?php echo $label ?></option>
                                <?php endforeach; ?>
                            </select>
                            <button class='btn btn-default' type="submit" style="display: inline-block;">Submit</button>
                        </div>
                    </div>
                    <input type='hidden' name='r' value='admin/listuser'>
                </form>
            <?php endif; ?>

            <table class="table">
                <thead>
                    <tr>
                        <th width='50px'>#</th>
                        <th width='450px'>ชื่อ</th>
                        <th width='75px'>อำเภอ</th>
                        <th>ดูรายละเอียด</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($user as $each_user): ?>
                        <tr>
                            <td><?php echo $each_user->uid ?></td>
                            <td><?php echo $each_user->realname ?></td>
                            <td><?php echo Yii::$app->params["amphor"][$each_user->province] ?></td>
                            <td><a href='<?php echo Yii::$app->urlManager->createUrl(["admin/userinfo", "uid" => $each_user->uid]) ?>' class='btn btn-default'>View</a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

views/admin/nav_menu.php
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">FDACMI</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo Yii::$app->urlManager->createUrl("admin/index") ?>">Welcome</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">User Manager <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?php echo Yii::$app->urlManager->createUrl("admin/listuser") ?>">List of User</a></li>
                        <?php if ($auth["level"] == 1): ?>
                            <li><a href="<?php echo Yii::$app->urlManager->createUrl("admin/createuser") ?>">Create new User</a></li>
                        <?php endif; ?>
                        <li class="divider"></li>
                        <li><a href="<?php echo Yii::$app->urlManager->createUrl(["admin/userinfo", "uid" => $auth["uid"]]) ?>">My Profile</a></li>
                    </ul>
                </li>
                <li><a href="<?php echo Yii::$app->urlManager->createUrl("admin/upload") ?>">Upload File</a></li>
                <li><a href="<?php echo Yii::$app->urlManager->baseUrl; ?>/webboard">Webboard</li>
            </ul>
            <p class="navbar-text navbar-right">Signed in as <a href="<?php echo Yii::$app->urlManager->createUrl(["admin/userinfo", "uid" => $auth["uid"]]) ?>" class="navbar-link"><?php echo $auth['realname'] ?></a> <a href="<?php echo Yii::$app->urlManager->createAbsoluteUrl("site/logout") ?>" class="btn btn-xs btn-danger">Log out</a></p>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

views/admin/uploadfile.php
<div class="container">
    <h3>ระบบอัพโหลดไฟล์</h3>
    <div class="row" style="background-color: #efefef;">
        <div class="col-xs-9 col-xs-offset-3" style="background-color: #fff;">
            <form class='form-horizontal' enctype="multipart/form-data" id='uploadfile_form' method='post' action='<?php echo Yii::$app->urlManager->createUrl("api/uploadallfile") ?>'>
                <label>หัวข้อ</label>
                <div class='form-group'>
                    <div class='col-xs-12'>
                        <input type='text' class='form-control' required="" name='subject'>
                    </div>
                </div>

                <label>เลือกไฟล์</label>
                <div class='form-group'>
                    <div class='col-xs-12'>
                        <input type='file' name='file_upload_zxc'>
                    </div>
                </div>

                <label>รายละเอียด</label>
                <div class='form-group'>
                    <div class='col-xs-12'>
                        <textarea class='form-control' name='detail' rows="12" required=""></textarea>
                    </div>
                </div>

                <div class='form-group'>
                    <div class='col-xs-12'>
                        <span id='spin'><img src='/wp-admin/images/spinner.gif'></span>
                        <button class='btn btn-primary' id='submit_btn' type='submit'><i class='glyphicon glyphicon-upload' data-loading-text='Uploading...'></i>&nbsp;Upload</button>
                        <button class='btn btn-danger' type='reset'><i class='glyphicon glyphicon-refresh'></i>&nbsp;Reset</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<style>
    #spin{
        display:none;
    }
</style>
<script type='text/javascript'>
    $(function () {
        $('#uploadfile_form').ajaxForm({
            beforeSend: function () {
                $('#submit_btn').button("loading");
                $('#spin').show();
            },
            uploadProgress: function (event, position, total, percentComplete) {
                console.log(percentComplete);
            },
            complete: function (xhr) {
                var json = $.parseJSON(xhr.responseText);
                if (json.status === "success") {
                    swal({title: "สำเร็จ", text: "ระบบได้ทำการอัพโหลดข้อมูลสำเร็จ", type: "success"}, function () {
                        location.href = json.link;
                    });
                } else {
                    swal({title: "ล้มเหลว", text: "ระบบไม่สามารถอัพโหลดข้อมูล", type: "error"});
                }

                $('#submit_btn').button("reset");
            }
        });
    });
</script>

views/admin/userinfo_edit.php
<div class="container">
    <div class="row" style="background-color: #efefef;">
        <div class="col-xs-3">
            <div class="panel panel-default" style="margin-top: 15px;">
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="<?php echo Yii::$app->urlManager->createUrl("admin/listuser") ?>">List of User</a></li>
                        <?php if (Yii::$app->controller->session["auth"]["level"] == 1): ?>
                            <li><a href="<?php echo Yii::$app->urlManager->createUrl("admin/createuser") ?>">Create new User</a></li>
                        <?php endif; ?>
                        <li><a href="<?php echo Yii::$app->urlManager->createUrl(["admin/userinfo", "uid" => Yii::$app->controller->session["auth"]["uid"]]) ?>">My Profile</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xs-9" style="background-color: #fff;">
            <h3>Application form</h3>
            <form class="form-horizontal" method="post" action="<?php echo Yii::$app->urlManager->createUrl("api/updateuser") ?>" id="regist_form">
                <label>ชื่อ - นามสกุล</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input type="text" class="form-control" name="realname" placeholder="ชื่อ สกุล" required="" value='<?php echo $userinfo->realname; ?>'>
                    </div>
                </div>

                <label>Username</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input type="text" class="form-control" name="username" placeholder="ชื่อเข้าใช้งาน" required="" value='<?php echo $userinfo->username; ?>' readonly="">
                    </div>
                </div>

                <label>Password</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input type="password" class="form-control" name="password" placeholder="รหัสผ่านเข้าใช้งาน" required="" value='xxxxx'>
                    </div>
                </div>

                <label>Email</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input type="email" class="form-control" name="email" placeholder="Email" required="" value='<?php echo $userinfo->email; ?>'>
                    </div>
                </div>

                <label>ระดับผู้ใช้งาน</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <select name="level" class="form-control">
                            <?php foreach (Yii::$app->params["userlevel"] as $val => $label): ?>
                                <option value="<?php echo $val ?>" <?php echo $userinfo->level == $val ? "selected" : ""; ?>><?php echo $label ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <label>ประจำอำเภอ</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <select name="province" class="form-control">
                            <?php foreach (Yii::$app->params["amphor"] as $val => $label): ?>
                                <option value="<?php echo $val ?>" <?php echo $userinfo->province == $val ? "selected" : ""; ?>><?php echo $label ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-12">
                        <button type="submit" class="btn btn-primary" id="submit_btn" data-loading-text="Updating..."><i class="glyphicon glyphicon-upload"></i>&nbsp;Update</button>
                        <button type="reset" class="btn btn-danger"><i class="glyphicon glyphicon-refresh"></i>&nbsp;Reset</button>
                    </div>
                </div>
                <input type='hidden' value='<?php echo $userinfo->uid ?>' name='uid'>
            </form>
        </div>
    </div>
</div>

<script typr="text/javascript">
    $(function () {
        $('#regist_form').ajaxForm({
            beforeSend: function () {
                $('#submit_btn').button('loading');
            },
            complete: function (xhr) {
                var json = $.parseJSON(xhr.responseText);
                if (json.status === "success") {
                    swal({"title": "สำเร็จ", "text": "ระบบได้ทำการอัพเดตบัญชีผู้ใช้งานเรียบร้อยแล้ว", "type": "success"}, function () {
                        location.reload();
                    });
                } else {
                    swal({"title": "ล้มเหลว", "text": "ระบบไม่สามารถอัพเดตบัญชีผู้ใช้งาน", "type": "error"});
                }
                $('#submit_btn').button('reset');
            }
        });
    });
</script>

views/admin/userinfo_view.php
<div class="container">
    <div class="row" style="background-color: #efefef;">
        <div class="col-xs-3">
            <div class="panel panel-default" style="margin-top: 15px;">
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="<?php echo Yii::$app->urlManager->createUrl("admin/listuser") ?>">List of User</a></li>
                        <?php if (Yii::$app->controller->session["auth"]["level"] == 1): ?>
                            <li><a href="<?php echo Yii::$app->urlManager->createUrl("admin/createuser") ?>">Create new User</a></li>
                        <?php endif; ?>
                        <li><a href="<?php echo Yii::$app->urlManager->createUrl(["admin/userinfo", "uid" => Yii::$app->controller->session["auth"]["uid"]]) ?>">My Profile</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xs-9" style="background-color: #fff;">
            <h3>Application form</h3>
            <form class="form-horizontal" method="post" id="regist_form">
                <label>ชื่อ - นามสกุล</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input type="text" class="form-control" name="realname" placeholder="ชื่อ สกุล" required="" value='<?php echo $userinfo->realname; ?>' readonly="">
                    </div>
                </div>

                <label>Username</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input type="text" class="form-control" name="username" placeholder="ชื่อเข้าใช้งาน" required="" value='<?php echo $userinfo->username; ?>' readonly="">
                    </div>
                </div>

                <label>Email</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input type="email" class="form-control" name="email" placeholder="Email" required="" value='<?php echo $userinfo->email; ?>' readonly="">
                    </div>
                </div>

                <label>ระดับผู้ใช้งาน</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <select name="level" class="form-control" readonly="">
                            <?php foreach (Yii::$app->params["userlevel"] as $val => $label): ?>
                                <option value="<?php echo $val ?>" <?php echo $userinfo->level == $val ? "selected" : ""; ?>><?php echo $label ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <label>ประจำอำเภอ</label>
                <div class="form-group">
                    <div class="col-xs-12">
                        <select name="province" class="form-control" readonly="">
                            <?php foreach (Yii::$app->params["amphor"] as $val => $label): ?>
                                <option value="<?php echo $val ?>" <?php echo $userinfo->province == $val ? "selected" : ""; ?>><?php echo $label ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>